# Generated by Django 4.2.5 on 2023-10-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotacao', models.FloatField()),
                ('ffo_yield', models.FloatField()),
                ('dividend_yield', models.FloatField()),
                ('p_vp', models.FloatField()),
                ('valor_mercado', models.FloatField()),
                ('liquidez', models.FloatField()),
                ('cap_rate', models.FloatField()),
                ('vacancia', models.FloatField()),
            ],
        ),
    ]
